# frozen_string_literal: true

source 'https://rubygems.org'
ruby '3.3.0'

# Rails framework
gem 'rails', '~> 7.1.0'

# Testing
group :development, :test do
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails'
  gem 'faker'
end

group :test do
  gem 'simplecov', require: false
  gem 'webmock'
end

# Database
gem 'pg', '~> 1.5'

# Puma web server
gem 'puma', '~> 6.0'

# Development tools
group :development do
  gem 'debug'
end

# Code quality
gem 'rubocop', require: false
gem 'rubocop-rails', require: false

# Optional: Admin namespace support
gem 'pundit', '~> 2.3'
gem 'active_model_serializers', '~> 0.10'
